-- Neurelo Generated Migration
-- Description: This migration was automatically generated by Neurelo
/*
Warnings:

- The primary key for the `users` table will be changed. If it partially fails, the table could be left without primary key constraint.
- You are about to drop the column `user_id` on the `users` table. All the data in the column will be lost.
- You are about to drop the `comments` table. If the table is not empty, all the data it contains will be lost.
- You are about to drop the `posts` table. If the table is not empty, all the data it contains will be lost.
- Added the required column `displayName` to the `users` table without a default value. This is not possible if the table is not empty.
- Added the required column `id` to the `users` table without a default value. This is not possible if the table is not empty.
- Added the required column `password` to the `users` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE `comments`
DROP FOREIGN KEY `comments_post_id_fkey`;

-- DropForeignKey
ALTER TABLE `comments`
DROP FOREIGN KEY `comments_user_id_fkey`;

-- DropForeignKey
ALTER TABLE `posts`
DROP FOREIGN KEY `posts_user_id_fkey`;

-- AlterTable
ALTER TABLE `users`
DROP PRIMARY KEY,
DROP COLUMN `user_id`,
ADD COLUMN `displayName` VARCHAR(191) NOT NULL,
ADD COLUMN `id` INTEGER NOT NULL AUTO_INCREMENT,
ADD COLUMN `password` VARCHAR(191) NOT NULL,
ADD PRIMARY KEY (`id`);

-- DropTable
DROP TABLE `comments`;

-- DropTable
DROP TABLE `posts`;