-- Neurelo Generated Migration
-- Description: This migration was automatically generated by Neurelo
/*
Warnings:

- You are about to alter the column `Number` on the `Lego` table. The data in that column could be lost. The data in that column will be cast from `VarChar(191)` to `Int`.

*/
-- AlterTable
ALTER TABLE `Lego` MODIFY `Number` INTEGER NOT NULL;