-- Neurelo Generated Migration
-- Description: This migration was automatically generated by Neurelo
/*
Warnings:

- The primary key for the `Account` table will be changed. If it partially fails, the table could be left without primary key constraint.
- You are about to drop the column `UID` on the `Account` table. All the data in the column will be lost.
- You are about to drop the column `AccountUID` on the `Billing` table. All the data in the column will be lost.
- Added the required column `ID` to the `Account` table without a default value. This is not possible if the table is not empty.
- Added the required column `AccountID` to the `Billing` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE `Billing`
DROP FOREIGN KEY `Billing_AccountUID_fkey`;

-- AlterTable
ALTER TABLE `Account`
DROP PRIMARY KEY,
DROP COLUMN `UID`,
ADD COLUMN `ID` INTEGER NOT NULL,
ADD PRIMARY KEY (`ID`);

-- AlterTable
ALTER TABLE `Billing`
DROP COLUMN `AccountUID`,
ADD COLUMN `AccountID` INTEGER NOT NULL;

-- AddForeignKey
ALTER TABLE `Billing` ADD CONSTRAINT `Billing_AccountID_fkey` FOREIGN KEY (`AccountID`) REFERENCES `Account` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;