-- Neurelo Generated Migration
-- Description: This migration was automatically generated by Neurelo
-- AlterTable
ALTER TABLE `Account`
ADD COLUMN `ProfilePicUrl` VARCHAR(191) NULL,
MODIFY `Address` VARCHAR(191) NULL,
MODIFY `DisplayName` VARCHAR(191) NULL,
MODIFY `PhoneNumber` VARCHAR(191) NULL;